version: 0.2

phases:
  install:
    commands:
      - echo Installing jq...
      - yum install -y jq

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - |
        CURRENT_IMAGE_VERSION=$(aws secretsmanager get-secret-value --secret-id $IMAGE_TAG_SECRET_ID --query "SecretString" --output text | jq -r '.IMAGE_TAG')
        echo "Current image version: $CURRENT_IMAGE_VERSION"

        MAJOR_VERSION=$(echo $CURRENT_IMAGE_VERSION | cut -d. -f1)
        MINOR_VERSION=$(echo $CURRENT_IMAGE_VERSION | cut -d. -f2)

        if [ "$MAJOR_VERSION" -eq 1 ] && [ "$MINOR_VERSION" -lt 9 ]; then
          NEXT_MINOR_VERSION=$((MINOR_VERSION + 1))
          NEXT_IMAGE_VERSION="${MAJOR_VERSION}.${NEXT_MINOR_VERSION}"
        elif [ "$MAJOR_VERSION" -eq 1 ] && [ "$MINOR_VERSION" -eq 9 ]; then
          NEXT_IMAGE_VERSION="2.0.0"
        elif [ "$MAJOR_VERSION" -eq 2 ] && [ "$MINOR_VERSION" -lt 9 ]; then
          NEXT_MINOR_VERSION=$((MINOR_VERSION + 1))
          NEXT_IMAGE_VERSION="${MAJOR_VERSION}.${NEXT_MINOR_VERSION}"
        else
          echo "Versioning limit exceeded or incorrect format."
          exit 1
        fi

        echo "Next image version: $NEXT_IMAGE_VERSION"

        export IMAGE_TAG=$NEXT_IMAGE_VERSION
        export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG >  imagedefinitions.json
      - |
        aws secretsmanager put-secret-value --secret-id $IMAGE_TAG_SECRET_ID --secret-string "{\"IMAGE_TAG\": \"$IMAGE_TAG\"}"

artifacts:
  files:
    - imagedefinitions.json
