version: 0.2

phases:
  install:
    commands:
      - echo Installing jq...
      - yum install -y jq

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      
      # Fetching current image version from Secrets Manager
      - |
        export CURRENT_IMAGE_VERSION=$(aws secretsmanager get-secret-value --secret-id $IMAGE_TAG_SECRET_ID --query "SecretString" --output text | jq -r '.IMAGE_TAG' || echo "1.0")
        echo "Current image version: $CURRENT_IMAGE_VERSION"

        # Parse the major and minor version numbers
        MAJOR_VERSION=$(echo $CURRENT_IMAGE_VERSION | cut -d. -f1)
        MINOR_VERSION=$(echo $CURRENT_IMAGE_VERSION | cut -d. -f2)

        # Determine the next version
        if [ "$MINOR_VERSION" -lt 9 ]; then
          NEXT_MINOR_VERSION=$((MINOR_VERSION + 1))
        else
          NEXT_MAJOR_VERSION=$((MAJOR_VERSION + 1))
          NEXT_MINOR_VERSION=0
        fi
        export NEXT_IMAGE_VERSION="${NEXT_MAJOR_VERSION}.${NEXT_MINOR_VERSION}"
        echo "Next image version: $NEXT_IMAGE_VERSION"

        # Update image version in Secrets Manager
        aws secretsmanager put-secret-value --secret-id $IMAGE_TAG_SECRET_ID --secret-string "{\"IMAGE_TAG\": \"$NEXT_IMAGE_VERSION\"}"

        # Set the current image tag
        export IMAGE_TAG=$CURRENT_IMAGE_VERSION

        # Set repository URI
        export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

        # Logging into ECR
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
